version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/java/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" 
    directory: "/spring/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/java/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/dart/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/flutter/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/gradle/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/typescript/"
    schedule:
      interval: "daily"
