version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/java/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/java/"
    schedule:
      interval: "daily"
