name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/jmewes/action-dependabot-auto-merge
      - uses: jmewes/action-dependabot-auto-merge@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
