name: automatically merge upgrades

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]') || (github.actor == 'jmewes') }}
    steps:
      - uses: actions/checkout@v2
      - env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
